version: '3.8'

networks:
  default:
    external: true
    name: "rfidNetwork"


services:
  nginx:
    image: nginx:stable
    container_name: rfid-web
    ports:
      - 8083:80
    volumes:
      - .:/var/www/r_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php


#without php, composer is nothing
  php:
    build:
      context: ./docker
      dockerfile: DockerFile
    container_name: rfid-php
    volumes:
      - .:/var/www/r_app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      #local.ini can carry the unhandled limitation of volumes

    restart: unless-stopped